apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-killer
  namespace: ns-killer
  labels:
    app.kubernetes.io/name: ns-killer
    app.kubernetes.io/ns-killer: ns-killer
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Germain
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ns-killer
      app.kubernetes.io/ns-killer: ns-killer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ns-killer
        app.kubernetes.io/ns-killer: ns-killer
    spec:
      serviceAccountName: ns-killer
      containers:
        - name: ns-killer
          image: "germainlefebvre4/k8s_ns-killer"
          #image: "eu.gcr.io/core-prof-social-pf-dsip/alpine:latest"
          imagePullPolicy: Always
          stdin: true
          tty: true
          env:
            - name: NS_PATTERN
              value: ".*"
            - name: NS_RETENTION_KIND
              value: "hours"
            - name: NS_RETENTION_TIME
              value: "1"
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
