name: Python application

on:
  push:
    branches:
    - master
    - feat/*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubectl_version:
          - 1.16.4
          - 1.15.7
          - 1.14.10
          - 1.13.13
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg KUBECTL_VERSION=${{ matrix.kubectl_version }} --tag germainlefebvre4/ns-killer:v${{ matrix.kubectl_version }}
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: germainlefebvre4/ns-killer:latest
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
